[project]
name = "barnes-hut-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hsluv>=5.0.4",
    "numpy>=2.2.6",
    "pygame>=2.6.1",
]
